# SAMPLE DEPLOYMENT FOR ACCOUNT SERVICE
apiVersion: v1
kind: Namespace
metadata:
  name: accounts
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: accounts
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - image: georgegoh/pod-stress:latest
        name: accounts
        ports:
        - containerPort: 5000
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: accounts
  labels:
    app: accounts
  name: accounts
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: accounts
  type: LoadBalancer # change service type if required.